name: mobile_amazonia
description: "Aplicativo de turismo sustentável na Amazônia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.5.0
  google_maps_flutter: ^2.12.3
  logger: ^2.0.2
  sentry_flutter: ^8.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3