name: mobile_amazonia
description: "Aplicativo de turismo sustentável na Amazônia com sistema de gamificação"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.5.0
  google_maps_flutter: ^2.12.3
  logger: ^2.0.2
  sentry_flutter: ^8.6.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
  uses-material-design: true