import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Firebase configuration placeholder.
///
/// Execute `flutterfire configure` and replace the values below with the
/// generated configuration for each platform before running the app.
class DefaultFirebaseOptions {
  /// Returns platform specific [FirebaseOptions].
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR17WJ7_Dws7OUJ2mh6Q58UHXcqwjD4Ok',
    appId: '1:921007120341:web:a2f702a14bf5e20fdc675c',
    messagingSenderId: '921007120341',
    projectId: 'ia-xp-app',
    authDomain: 'ia-xp-app.firebaseapp.com',
    storageBucket: 'ia-xp-app.firebasestorage.app',
    measurementId: 'G-W8KPZGL4MR',
  );

  /// Web configuration generated by FlutterFire CLI.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjoZXDxbw70Dw1lKvUnGWD1JFjOu2JKnY',
    appId: '1:921007120341:android:3c508ca9fd50fbdddc675c',
    messagingSenderId: '921007120341',
    projectId: 'ia-xp-app',
    storageBucket: 'ia-xp-app.firebasestorage.app',
  );

  /// Android configuration generated by FlutterFire CLI.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxVLCxnkMWHwjQXp6g3S7T5Reus02cODA',
    appId: '1:921007120341:ios:73225773cb3f5f8fdc675c',
    messagingSenderId: '921007120341',
    projectId: 'ia-xp-app',
    storageBucket: 'ia-xp-app.firebasestorage.app',
    iosBundleId: 'com.example.mobileAmazonia',
  );

  /// iOS configuration generated by FlutterFire CLI.

  /// macOS configuration generated by FlutterFire CLI.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'CHANGE_ME',
    appId: 'CHANGE_ME',
    messagingSenderId: 'CHANGE_ME',
    projectId: 'CHANGE_ME',
    storageBucket: 'CHANGE_ME.appspot.com',
    iosBundleId: 'com.example.app',
  );

  /// Windows configuration generated by FlutterFire CLI.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'CHANGE_ME',
    appId: 'CHANGE_ME',
    messagingSenderId: 'CHANGE_ME',
    projectId: 'CHANGE_ME',
    storageBucket: 'CHANGE_ME.appspot.com',
  );

  /// Linux configuration generated by FlutterFire CLI.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'CHANGE_ME',
    appId: 'CHANGE_ME',
    messagingSenderId: 'CHANGE_ME',
    projectId: 'CHANGE_ME',
    storageBucket: 'CHANGE_ME.appspot.com',
  );
}